### ISSUE TITLE
First MVP checklist:

### ISSUE THREAD

**Issue by peterniemeier** [peterniemeier/Playables#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [ ] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [ ] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
 - [ ] Errors should display for both `/signup` and`/login`.
 - [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
 - [x] Demo Login Works

**Comment by rkoron007** [comment]
Make sure to update your Live site link on your Wiki for heroku so I can grade this :)

**Comment by rkoron007** [comment]
- Make sure errors are being displayed for login and sign up 


## Styling:
- For `Navbar`:
- Have a little mascot buddy on controller icon in your navbar
![screen shot 2018-10-18 at 10 12 45 am](https://user-images.githubusercontent.com/32436232/47171763-76969780-d2be-11e8-98d1-558db58d8c27.png)

**Comment by rkoron007** [comment]
Let me know if you'd like me to re-review this!
